---
include:
  - board: eyelash_sofle_left
    shield: nice_view_adapter nice_view_gem
  - board: eyelash_sofle_right
    shield: nice_view_adapter nice_view_gem
  - board: eyelash_sofle_left
    shield: settings_reset
